build(firefox): check file size
if building `firefox` or `firefox-mv3`

    * check if any file(s) exceeds 4M (megabytes)

        - If true, fail and provide basic message.

diff --git a/.github/workflows/build-browser.yml b/.github/workflows/build-browser.yml
--- a/.github/workflows/build-browser.yml
+++ b/.github/workflows/build-browser.yml
@@ -246,6 +246,27 @@ jobs:
           unzip browser-source.zip
           rm browser-source.zip
 
+      - name: Check source file size
+        if: ${{ startsWith(matrix.name, 'firefox') }}
+        run: |
+          # Declare variable as indexed array
+          declare -a FILES
+
+          # Search for source files that are greater than 4M
+          while IFS=' ' read -r RESULT; do
+              FILES+=("$RESULT")
+          done < <(find ./browser-source -size +4M)
+
+          # Validate results and provide messaging
+          if [[ ${#FILES[@]} -ne 0 ]]; then
+              echo "File(s) exceeds size limit: 4M"
+              for FILE in ${FILES[@]}; do
+                  echo "- $(du --si $FILE)"
+              done
+              # Invoke failure
+              exit 1
+          fi
+
       - name: NPM setup
         run: npm ci
         working-directory: browser-source/
