edit file for testing

diff --git a/.github/workflows/publish-desktop.yml b/.github/workflows/publish-desktop.yml
--- a/.github/workflows/publish-desktop.yml
+++ b/.github/workflows/publish-desktop.yml
@@ -109,203 +109,203 @@ jobs:
               ;;
           esac
 
-      - name: Create GitHub deployment
-        if: ${{ inputs.publish_type != 'Dry Run' }}
-        uses: chrnorm/deployment-action@55729fcebec3d284f60f5bcabbd8376437d696b1 # v2.0.7
-        id: deployment
-        with:
-          token: '${{ secrets.GITHUB_TOKEN }}'
-          initial-status: 'in_progress'
-          environment: 'Desktop - Production'
-          description: 'Deployment ${{ steps.version.outputs.version }} to channel ${{ steps.release_channel.outputs.channel }} from branch ${{ github.ref_name }}'
-          task: release
+      # - name: Create GitHub deployment
+      #   if: ${{ inputs.publish_type != 'Dry Run' }}
+      #   uses: chrnorm/deployment-action@55729fcebec3d284f60f5bcabbd8376437d696b1 # v2.0.7
+      #   id: deployment
+      #   with:
+      #     token: '${{ secrets.GITHUB_TOKEN }}'
+      #     initial-status: 'in_progress'
+      #     environment: 'Desktop - Production'
+      #     description: 'Deployment ${{ steps.version.outputs.version }} to channel ${{ steps.release_channel.outputs.channel }} from branch ${{ github.ref_name }}'
+      #     task: release
 
-  electron-blob:
-    name: Electron blob publish
-    runs-on: ubuntu-22.04
-    needs: setup
-    permissions:
-      contents: read
-      packages: read
-      id-token: write
-      deployments: write
-    env:
-      _PKG_VERSION: ${{ needs.setup.outputs.release_version }}
-      _RELEASE_TAG: ${{ needs.setup.outputs.tag_name }}
-    steps:
-      - name: Log in to Azure
-        uses: bitwarden/gh-actions/azure-login@main
-        with:
-          subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
-          tenant_id: ${{ secrets.AZURE_TENANT_ID }}
-          client_id: ${{ secrets.AZURE_CLIENT_ID }}
+  # electron-blob:
+  #   name: Electron blob publish
+  #   runs-on: ubuntu-22.04
+  #   needs: setup
+  #   permissions:
+  #     contents: read
+  #     packages: read
+  #     id-token: write
+  #     deployments: write
+  #   env:
+  #     _PKG_VERSION: ${{ needs.setup.outputs.release_version }}
+  #     _RELEASE_TAG: ${{ needs.setup.outputs.tag_name }}
+  #   steps:
+  #     - name: Log in to Azure
+  #       uses: bitwarden/gh-actions/azure-login@main
+  #       with:
+  #         subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
+  #         tenant_id: ${{ secrets.AZURE_TENANT_ID }}
+  #         client_id: ${{ secrets.AZURE_CLIENT_ID }}
 
-      - name: Retrieve secrets
-        id: retrieve-secrets
-        uses: bitwarden/gh-actions/get-keyvault-secrets@main
-        with:
-          keyvault: "bitwarden-ci"
-          secrets: "aws-electron-access-id,
-            aws-electron-access-key,
-            aws-electron-bucket-name"
+  #     - name: Retrieve secrets
+  #       id: retrieve-secrets
+  #       uses: bitwarden/gh-actions/get-keyvault-secrets@main
+  #       with:
+  #         keyvault: "bitwarden-ci"
+  #         secrets: "aws-electron-access-id,
+  #           aws-electron-access-key,
+  #           aws-electron-bucket-name"
 
-      - name: Log out from Azure
-        uses: bitwarden/gh-actions/azure-logout@main
+  #     - name: Log out from Azure
+  #       uses: bitwarden/gh-actions/azure-logout@main
 
-      - name: Create artifacts directory
-        run: mkdir -p apps/desktop/artifacts
+  #     - name: Create artifacts directory
+  #       run: mkdir -p apps/desktop/artifacts
 
-      - name: Download artifacts
-        env:
-          GH_TOKEN: ${{ github.token }}
-        working-directory: apps/desktop/artifacts
-        run: gh release download ${{ env._RELEASE_TAG }} -R bitwarden/clients
+  #     - name: Download artifacts
+  #       env:
+  #         GH_TOKEN: ${{ github.token }}
+  #       working-directory: apps/desktop/artifacts
+  #       run: gh release download ${{ env._RELEASE_TAG }} -R bitwarden/clients
 
-      - name: Set staged rollout percentage
-        env:
-          RELEASE_CHANNEL: ${{ needs.setup.outputs.release_channel }}
-          ROLLOUT_PCT: ${{ inputs.electron_rollout_percentage }}
-        run: |
-          echo "stagingPercentage: ${ROLLOUT_PCT}" >> apps/desktop/artifacts/${RELEASE_CHANNEL}.yml
-          echo "stagingPercentage: ${ROLLOUT_PCT}" >> apps/desktop/artifacts/${RELEASE_CHANNEL}-linux.yml
-          echo "stagingPercentage: ${ROLLOUT_PCT}" >> apps/desktop/artifacts/${RELEASE_CHANNEL}-mac.yml
+  #     - name: Set staged rollout percentage
+  #       env:
+  #         RELEASE_CHANNEL: ${{ needs.setup.outputs.release_channel }}
+  #         ROLLOUT_PCT: ${{ inputs.electron_rollout_percentage }}
+  #       run: |
+  #         echo "stagingPercentage: ${ROLLOUT_PCT}" >> apps/desktop/artifacts/${RELEASE_CHANNEL}.yml
+  #         echo "stagingPercentage: ${ROLLOUT_PCT}" >> apps/desktop/artifacts/${RELEASE_CHANNEL}-linux.yml
+  #         echo "stagingPercentage: ${ROLLOUT_PCT}" >> apps/desktop/artifacts/${RELEASE_CHANNEL}-mac.yml
 
-      - name: Publish artifacts to S3
-        if: ${{ inputs.publish_type != 'Dry Run' }}
-        env:
-          AWS_ACCESS_KEY_ID: ${{ steps.retrieve-secrets.outputs.aws-electron-access-id }}
-          AWS_SECRET_ACCESS_KEY: ${{ steps.retrieve-secrets.outputs.aws-electron-access-key }}
-          AWS_DEFAULT_REGION: 'us-west-2'
-          AWS_S3_BUCKET_NAME: ${{ steps.retrieve-secrets.outputs.aws-electron-bucket-name }}
-        working-directory: apps/desktop/artifacts
-        run: |
-          aws s3 cp ./ $AWS_S3_BUCKET_NAME/desktop/ \
-          --acl "public-read" \
-          --recursive \
-          --quiet
+  #     - name: Publish artifacts to S3
+  #       if: ${{ inputs.publish_type != 'Dry Run' }}
+  #       env:
+  #         AWS_ACCESS_KEY_ID: ${{ steps.retrieve-secrets.outputs.aws-electron-access-id }}
+  #         AWS_SECRET_ACCESS_KEY: ${{ steps.retrieve-secrets.outputs.aws-electron-access-key }}
+  #         AWS_DEFAULT_REGION: 'us-west-2'
+  #         AWS_S3_BUCKET_NAME: ${{ steps.retrieve-secrets.outputs.aws-electron-bucket-name }}
+  #       working-directory: apps/desktop/artifacts
+  #       run: |
+  #         aws s3 cp ./ $AWS_S3_BUCKET_NAME/desktop/ \
+  #         --acl "public-read" \
+  #         --recursive \
+  #         --quiet
 
-      - name: Update deployment status to Success
-        if: ${{ inputs.publish_type != 'Dry Run' && success() }}
-        uses: chrnorm/deployment-status@9a72af4586197112e0491ea843682b5dc280d806 # v2.0.3
-        with:
-          token: '${{ secrets.GITHUB_TOKEN }}'
-          state: 'success'
-          deployment-id: ${{ needs.setup.outputs.deployment_id }}
+  #     - name: Update deployment status to Success
+  #       if: ${{ inputs.publish_type != 'Dry Run' && success() }}
+  #       uses: chrnorm/deployment-status@9a72af4586197112e0491ea843682b5dc280d806 # v2.0.3
+  #       with:
+  #         token: '${{ secrets.GITHUB_TOKEN }}'
+  #         state: 'success'
+  #         deployment-id: ${{ needs.setup.outputs.deployment_id }}
 
-      - name: Update deployment status to Failure
-        if: ${{ inputs.publish_type != 'Dry Run' && failure() }}
-        uses: chrnorm/deployment-status@9a72af4586197112e0491ea843682b5dc280d806 # v2.0.3
-        with:
-          token: '${{ secrets.GITHUB_TOKEN }}'
-          state: 'failure'
-          deployment-id: ${{ needs.setup.outputs.deployment_id }}
+  #     - name: Update deployment status to Failure
+  #       if: ${{ inputs.publish_type != 'Dry Run' && failure() }}
+  #       uses: chrnorm/deployment-status@9a72af4586197112e0491ea843682b5dc280d806 # v2.0.3
+  #       with:
+  #         token: '${{ secrets.GITHUB_TOKEN }}'
+  #         state: 'failure'
+  #         deployment-id: ${{ needs.setup.outputs.deployment_id }}
 
-  snap:
-    name: Deploy Snap
-    runs-on: ubuntu-22.04
-    needs: setup
-    permissions:
-      contents: read
-      id-token: write
-    if: inputs.snap_publish
-    env:
-      _PKG_VERSION: ${{ needs.setup.outputs.release_version }}
-      _RELEASE_TAG: ${{ needs.setup.outputs.tag_name }}
-    steps:
-      - name: Checkout Repo
-        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
+  # snap:
+  #   name: Deploy Snap
+  #   runs-on: ubuntu-22.04
+  #   needs: setup
+  #   permissions:
+  #     contents: read
+  #     id-token: write
+  #   if: inputs.snap_publish
+  #   env:
+  #     _PKG_VERSION: ${{ needs.setup.outputs.release_version }}
+  #     _RELEASE_TAG: ${{ needs.setup.outputs.tag_name }}
+  #   steps:
+  #     - name: Checkout Repo
+  #       uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
 
-      - name: Log in to Azure
-        uses: bitwarden/gh-actions/azure-login@main
-        with:
-          subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
-          tenant_id: ${{ secrets.AZURE_TENANT_ID }}
-          client_id: ${{ secrets.AZURE_CLIENT_ID }}
+  #     - name: Log in to Azure
+  #       uses: bitwarden/gh-actions/azure-login@main
+  #       with:
+  #         subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
+  #         tenant_id: ${{ secrets.AZURE_TENANT_ID }}
+  #         client_id: ${{ secrets.AZURE_CLIENT_ID }}
 
-      - name: Retrieve secrets
-        id: retrieve-secrets
-        uses: bitwarden/gh-actions/get-keyvault-secrets@main
-        with:
-          keyvault: "bitwarden-ci"
-          secrets: "snapcraft-store-token"
+  #     - name: Retrieve secrets
+  #       id: retrieve-secrets
+  #       uses: bitwarden/gh-actions/get-keyvault-secrets@main
+  #       with:
+  #         keyvault: "bitwarden-ci"
+  #         secrets: "snapcraft-store-token"
 
-      - name: Log out from Azure
-        uses: bitwarden/gh-actions/azure-logout@main
+  #     - name: Log out from Azure
+  #       uses: bitwarden/gh-actions/azure-logout@main
 
-      - name: Install Snap
-        uses: samuelmeuli/action-snapcraft@d33c176a9b784876d966f80fb1b461808edc0641 # v2.1.1
+  #     - name: Install Snap
+  #       uses: samuelmeuli/action-snapcraft@d33c176a9b784876d966f80fb1b461808edc0641 # v2.1.1
 
-      - name: Setup
-        run: mkdir dist
-        working-directory: apps/desktop
+  #     - name: Setup
+  #       run: mkdir dist
+  #       working-directory: apps/desktop
 
-      - name: Download artifacts
-        working-directory: apps/desktop/dist
-        run: wget https://github.com/bitwarden/clients/releases/download/${{ env._RELEASE_TAG }}/bitwarden_${{ env._PKG_VERSION }}_amd64.snap
+  #     - name: Download artifacts
+  #       working-directory: apps/desktop/dist
+  #       run: wget https://github.com/bitwarden/clients/releases/download/${{ env._RELEASE_TAG }}/bitwarden_${{ env._PKG_VERSION }}_amd64.snap
 
-      - name: Deploy to Snap Store
-        if: ${{ inputs.publish_type != 'Dry Run' }}
-        env:
-          SNAPCRAFT_STORE_CREDENTIALS: ${{ steps.retrieve-secrets.outputs.snapcraft-store-token }}
-        run: |
-          snapcraft upload bitwarden_${{ env._PKG_VERSION }}_amd64.snap --release stable
-          snapcraft logout
-        working-directory: apps/desktop/dist
+  #     - name: Deploy to Snap Store
+  #       if: ${{ inputs.publish_type != 'Dry Run' }}
+  #       env:
+  #         SNAPCRAFT_STORE_CREDENTIALS: ${{ steps.retrieve-secrets.outputs.snapcraft-store-token }}
+  #       run: |
+  #         snapcraft upload bitwarden_${{ env._PKG_VERSION }}_amd64.snap --release stable
+  #         snapcraft logout
+  #       working-directory: apps/desktop/dist
 
-  choco:
-    name: Deploy Choco
-    runs-on: windows-2022
-    needs: setup
-    permissions:
-      contents: read
-      id-token: write
-    if: inputs.choco_publish
-    env:
-      _PKG_VERSION: ${{ needs.setup.outputs.release_version }}
-      _RELEASE_TAG: ${{ needs.setup.outputs.tag_name }}
-    steps:
-      - name: Checkout Repo
-        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
+  # choco:
+  #   name: Deploy Choco
+  #   runs-on: windows-2022
+  #   needs: setup
+  #   permissions:
+  #     contents: read
+  #     id-token: write
+  #   if: inputs.choco_publish
+  #   env:
+  #     _PKG_VERSION: ${{ needs.setup.outputs.release_version }}
+  #     _RELEASE_TAG: ${{ needs.setup.outputs.tag_name }}
+  #   steps:
+  #     - name: Checkout Repo
+  #       uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
 
-      - name: Print Environment
-        run: |
-          dotnet --version
-          dotnet nuget --version
+  #     - name: Print Environment
+  #       run: |
+  #         dotnet --version
+  #         dotnet nuget --version
 
-      - name: Log in to Azure
-        uses: bitwarden/gh-actions/azure-login@main
-        with:
-          subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
-          tenant_id: ${{ secrets.AZURE_TENANT_ID }}
-          client_id: ${{ secrets.AZURE_CLIENT_ID }}
+  #     - name: Log in to Azure
+  #       uses: bitwarden/gh-actions/azure-login@main
+  #       with:
+  #         subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
+  #         tenant_id: ${{ secrets.AZURE_TENANT_ID }}
+  #         client_id: ${{ secrets.AZURE_CLIENT_ID }}
 
-      - name: Retrieve secrets
-        id: retrieve-secrets
-        uses: bitwarden/gh-actions/get-keyvault-secrets@main
-        with:
-          keyvault: "bitwarden-ci"
-          secrets: "cli-choco-api-key"
+  #     - name: Retrieve secrets
+  #       id: retrieve-secrets
+  #       uses: bitwarden/gh-actions/get-keyvault-secrets@main
+  #       with:
+  #         keyvault: "bitwarden-ci"
+  #         secrets: "cli-choco-api-key"
 
-      - name: Log out from Azure
-        uses: bitwarden/gh-actions/azure-logout@main
+  #     - name: Log out from Azure
+  #       uses: bitwarden/gh-actions/azure-logout@main
 
-      - name: Setup Chocolatey
-        run: choco apikey --key $env:CHOCO_API_KEY --source https://push.chocolatey.org/
-        env:
-          CHOCO_API_KEY: ${{ steps.retrieve-secrets.outputs.cli-choco-api-key }}
+  #     - name: Setup Chocolatey
+  #       run: choco apikey --key $env:CHOCO_API_KEY --source https://push.chocolatey.org/
+  #       env:
+  #         CHOCO_API_KEY: ${{ steps.retrieve-secrets.outputs.cli-choco-api-key }}
 
-      - name: Make dist dir
-        run: New-Item -ItemType directory -Path ./dist
-        working-directory: apps/desktop
+  #     - name: Make dist dir
+  #       run: New-Item -ItemType directory -Path ./dist
+  #       working-directory: apps/desktop
 
-      - name: Download artifacts
-        working-directory: apps/desktop/dist
-        run: Invoke-WebRequest -Uri "https://github.com/bitwarden/clients/releases/download/${{ env._RELEASE_TAG }}/bitwarden.${{ env._PKG_VERSION }}.nupkg" -OutFile bitwarden.${{ env._PKG_VERSION }}.nupkg
+  #     - name: Download artifacts
+  #       working-directory: apps/desktop/dist
+  #       run: Invoke-WebRequest -Uri "https://github.com/bitwarden/clients/releases/download/${{ env._RELEASE_TAG }}/bitwarden.${{ env._PKG_VERSION }}.nupkg" -OutFile bitwarden.${{ env._PKG_VERSION }}.nupkg
 
-      - name: Push to Chocolatey
-        if: ${{ inputs.publish_type != 'Dry Run' }}
-        run: choco push --source=https://push.chocolatey.org/
-        working-directory: apps/desktop/dist
+  #     - name: Push to Chocolatey
+  #       if: ${{ inputs.publish_type != 'Dry Run' }}
+  #       run: choco push --source=https://push.chocolatey.org/
+  #       working-directory: apps/desktop/dist
 
   mas:
     name: Deploy Mac App Store
@@ -395,36 +395,36 @@ jobs:
             dry_run:$IS_DRY_RUN \
             submit_for_review:"${{ inputs.auto_submit_for_review }}"
 
-  update-deployment:
-    name: Update Deployment Status
-    runs-on: ubuntu-22.04
-    needs:
-      - setup
-      - electron-blob
-      - snap
-      - choco
-      - mas
-    permissions:
-      contents: read
-      deployments: write
-    if: ${{ always() && inputs.publish_type != 'Dry Run' }}
-    steps:
-      - name: Check if any job failed
-        if: contains(needs.*.result, 'failure')
-        run: exit 1
+  # update-deployment:
+  #   name: Update Deployment Status
+  #   runs-on: ubuntu-22.04
+  #   needs:
+  #     - setup
+  #     - electron-blob
+  #     - snap
+  #     - choco
+  #     - mas
+  #   permissions:
+  #     contents: read
+  #     deployments: write
+  #   if: ${{ always() && inputs.publish_type != 'Dry Run' }}
+  #   steps:
+  #     - name: Check if any job failed
+  #       if: contains(needs.*.result, 'failure')
+  #       run: exit 1
 
-      - name: Update deployment status to Success
-        if: ${{ inputs.publish_type != 'Dry Run' && success() }}
-        uses: chrnorm/deployment-status@9a72af4586197112e0491ea843682b5dc280d806 # v2.0.3
-        with:
-          token: '${{ secrets.GITHUB_TOKEN }}'
-          state: 'success'
-          deployment-id: ${{ needs.setup.outputs.deployment_id }}
+  #     - name: Update deployment status to Success
+  #       if: ${{ inputs.publish_type != 'Dry Run' && success() }}
+  #       uses: chrnorm/deployment-status@9a72af4586197112e0491ea843682b5dc280d806 # v2.0.3
+  #       with:
+  #         token: '${{ secrets.GITHUB_TOKEN }}'
+  #         state: 'success'
+  #         deployment-id: ${{ needs.setup.outputs.deployment_id }}
 
-      - name: Update deployment status to Failure
-        if: ${{ inputs.publish_type != 'Dry Run' && failure() }}
-        uses: chrnorm/deployment-status@9a72af4586197112e0491ea843682b5dc280d806 # v2.0.3
-        with:
-          token: '${{ secrets.GITHUB_TOKEN }}'
-          state: 'failure'
-          deployment-id: ${{ needs.setup.outputs.deployment_id }}
+  #     - name: Update deployment status to Failure
+  #       if: ${{ inputs.publish_type != 'Dry Run' && failure() }}
+  #       uses: chrnorm/deployment-status@9a72af4586197112e0491ea843682b5dc280d806 # v2.0.3
+  #       with:
+  #         token: '${{ secrets.GITHUB_TOKEN }}'
+  #         state: 'failure'
+  #         deployment-id: ${{ needs.setup.outputs.deployment_id }}
