review: adjust logic of retries for npm ci

diff --git a/.github/workflows/sdk-breaking-change-check.yml b/.github/workflows/sdk-breaking-change-check.yml
--- a/.github/workflows/sdk-breaking-change-check.yml
+++ b/.github/workflows/sdk-breaking-change-check.yml
@@ -96,9 +96,9 @@ jobs:
             fi
           done
           
-          if [ ${RETRY_COUNT} -eq ${MAX_RETRIES} ] && ! npm ci; then
-            echo "::error::npm ci failed after ${MAX_RETRIES} attempts"
-            exit 1
+          if [ ${RETRY_COUNT} -eq ${MAX_RETRIES} ]; then
+             echo "::error::npm ci failed after ${MAX_RETRIES} attempts"
+             exit 1
           fi
 
       - name: Download SDK artifacts
